fn rust_string_literal(text: &str) -> String {
    let mut output = String::from("\"");
    for ch in text.chars() {
        match ch {
            '\\' => output.push_str("\\\\"),
            '"' => output.push_str("\\\""),
            '\n' => output.push_str("\\n"),
            '\r' => output.push_str("\\r"),
            '\t' => output.push_str("\\t"),
            '\0' => output.push_str("\\0"),
            ch if ch.is_ascii_graphic() || ch == ' ' => output.push(ch),
            ch => {
                use std::fmt::Write as _;
                write!(output, "\\u{{{:x}}}", ch as u32).expect("failed to write string escape");
            }
        }
    }
    output.push('"');
    output
}

fn rust_byte_string_literal(bytes: &[u8]) -> String {
    let mut output = String::from("b\"");
    for byte in bytes {
        match byte {
            b'\\' => output.push_str("\\\\"),
            b'"' => output.push_str("\\\""),
            b'\n' => output.push_str("\\n"),
            b'\r' => output.push_str("\\r"),
            b'\t' => output.push_str("\\t"),
            b'\0' => output.push_str("\\0"),
            0x20..=0x7e => output.push(*byte as char),
            byte => {
                use std::fmt::Write as _;
                write!(output, "\\x{:02x}", byte).expect("failed to write byte escape");
            }
        }
    }
    output.push('"');
    output
}

fn main() {
    let manifest_dir = std::env::var("CARGO_MANIFEST_DIR")
        .expect("CARGO_MANIFEST_DIR must be set by cargo");
    let assets_dir = std::path::Path::new(&manifest_dir).join("assets");
    let out_dir = std::path::PathBuf::from(
        std::env::var("OUT_DIR").expect("OUT_DIR must be set by cargo"),
    );
    let out_file = out_dir.join("embedded_assets_rust.rs");
    let stable_file = std::path::Path::new(&manifest_dir).join("embedded_assets_rust.oracle.rs");

    println!("cargo:rerun-if-changed=assets");
    println!("cargo:rerun-if-changed=assets/index.html");
    println!("cargo:rerun-if-changed=assets/assets/app.css");
    println!("cargo:rerun-if-changed=assets/assets/app.js");
    println!("cargo:rustc-env=EMBEDDED_ASSETS_RUST={}", out_file.display());

    let captured_assets = std::cell::RefCell::new(Vec::<(Vec<u8>, String, Vec<u8>)>::new());
    tauri_codegen::embedded_assets::EmbeddedAssets::new(
        assets_dir.clone(),
        &tauri_codegen::embedded_assets::AssetOptions::new(
            tauri_utils::config::PatternKind::Brownfield,
        ),
        |key, path, input, _csp_hashes| {
            #[cfg(unix)]
            use std::os::unix::ffi::OsStrExt as _;

            let relative = path
                .strip_prefix(&assets_dir)
                .expect("asset path must stay under the asset directory");
            captured_assets
                .borrow_mut()
                .push((
                    relative.as_os_str().as_bytes().to_vec(),
                    key.as_ref().to_owned(),
                    input.clone(),
                ));
            Ok::<(), tauri_codegen::embedded_assets::EmbeddedAssetsError>(())
        },
    )
    .expect("failed to generate embedded assets for the seam oracle");

    let mut assets = captured_assets.into_inner();
    assets.sort_by(|left, right| left.0.cmp(&right.0));
    let mut assets_by_key = std::collections::BTreeMap::<String, Vec<u8>>::new();
    for (_relative_bytes, key, bytes) in assets {
        assets_by_key.insert(key, bytes);
    }

    let mut source = String::new();
    source.push_str("// @generated by tools/tauri_embedded_assets_rust.py\n");
    source.push_str("// DO NOT EDIT.\n\n");
    source.push_str("pub const EMBEDDED_ASSETS: &[(&str, &[u8])] = &[\n");
    for (key, bytes) in assets_by_key {
        source.push_str("    (");
        source.push_str(&rust_string_literal(&key));
        source.push_str(", ");
        source.push_str(&rust_byte_string_literal(&bytes));
        source.push_str("),\n");
    }
    source.push_str("];\n");

    std::fs::write(&out_file, &source).unwrap_or_else(|error| {
        panic!("failed to write embedded assets oracle output {out_file:?}: {error}");
    });
    std::fs::write(&stable_file, source).unwrap_or_else(|error| {
        panic!("failed to write stable embedded assets oracle output {stable_file:?}: {error}");
    });
}
