#!/usr/bin/env python3

import argparse
import os
from pathlib import Path


def rust_string_literal(text: str) -> str:
    parts = ['"']
    for char in text:
        codepoint = ord(char)
        if char == "\\":
            parts.append(r"\\")
        elif char == '"':
            parts.append(r"\"")
        elif char == "\n":
            parts.append(r"\n")
        elif char == "\r":
            parts.append(r"\r")
        elif char == "\t":
            parts.append(r"\t")
        elif char == "\0":
            parts.append(r"\0")
        elif 0x20 <= codepoint <= 0x7E:
            parts.append(char)
        else:
            parts.append(f"\\u{{{codepoint:x}}}")
    parts.append('"')
    return "".join(parts)


def rust_byte_string_literal(data: bytes) -> str:
    parts = ['b"']
    for byte in data:
        if byte == 0x5C:
            parts.append(r"\\")
        elif byte == 0x22:
            parts.append(r"\"")
        elif byte == 0x0A:
            parts.append(r"\n")
        elif byte == 0x0D:
            parts.append(r"\r")
        elif byte == 0x09:
            parts.append(r"\t")
        elif byte == 0x00:
            parts.append(r"\0")
        elif 0x20 <= byte <= 0x7E:
            parts.append(chr(byte))
        else:
            parts.append(f"\\x{byte:02x}")
    parts.append('"')
    return "".join(parts)


def load_assets(root: Path) -> list[tuple[str, bytes]]:
    assets_by_key: dict[str, bytes] = {}
    for path in sorted(
        (path for path in root.rglob("*") if path.is_file()),
        key=lambda path: raw_asset_path(root, path),
    ):
        assets_by_key[asset_key(root, path)] = path.read_bytes()
    return sorted(assets_by_key.items(), key=lambda item: item[0])


def asset_key(root: Path, path: Path) -> str:
    relative = path.relative_to(root)
    parts = [
        os.fsencode(part).decode("utf-8", "replace")
        for part in relative.parts
    ]
    return "/" + "/".join(parts)


def raw_asset_path(root: Path, path: Path) -> bytes:
    relative = path.relative_to(root)
    return b"/".join(os.fsencode(part) for part in relative.parts)


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("input_dir")
    parser.add_argument("output_file")
    args = parser.parse_args()

    root = Path(args.input_dir)
    assets = load_assets(root)

    output = Path(args.output_file)
    output.parent.mkdir(parents=True, exist_ok=True)
    with output.open("w", encoding="utf-8", newline="\n") as stream:
        stream.write("// @generated by tools/tauri_embedded_assets_rust.py\n")
        stream.write("// DO NOT EDIT.\n\n")
        stream.write("pub const EMBEDDED_ASSETS: &[(&str, &[u8])] = &[\n")
        for key, content in assets:
            stream.write(
                f"    ({rust_string_literal(key)}, {rust_byte_string_literal(content)}),\n"
            )
        stream.write("];\n")

    return 0


if __name__ == "__main__":
    raise SystemExit(main())
