name: CI

on:
  push:
  pull_request:

jobs:
  examples:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - uses: bazel-contrib/setup-bazel@v1
      - name: Validate examples
        run: sh ./test/validate_examples.sh
